# **Basics of Numpy**


# Heading

In [2]:
import numpy as np
type(np.random.rand())

numpy.ndarray

In [26]:
a=np.arange(5)
#a=np.random.rand(5)
a=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]]) #2d
print(a)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


# Testing of 3d Array

In [60]:
threeD=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]]) #3d
print(threeD)
print(threeD[2,0,2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
21


In [39]:

a= np.ones((3,2,3))
a[0,0,1]=3
print(a);

[[[1. 3. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


**4. Print all the rows with only 'birds' and 'age' columns from the dataframe**

In [21]:
df[['birds','age']]


birds  age
0      Cranes  3.5
1      Cranes  4.0
2     plovers  1.5
3  spoonbills  0.0
4  spoonbills  6.0
5      Cranes  3.0
6     plovers  5.5
7      Cranes  0.0
8  spoonbills  8.0
9  spoonbills  4.0

**5. select [2, 3, 7] rows and in columns ['birds', 'age', 'visits']**

In [22]:
df[['birds','age', 'visits']].iloc[[1,2,6]]

birds  age  visits
1   Cranes  4.0       4
2  plovers  1.5       3
6  plovers  5.5       2

**6. select the rows where the number of visits is less than 4**

In [24]:
#Which one is best performance wise?
df.loc[df['visits'] < 4]
df[df['visits'] < 4]

birds  age  visits priority labels
0      Cranes  3.5       2      yes      a
2     plovers  1.5       3       no      c
4  spoonbills  6.0       3       no      e
6     plovers  5.5       2       no      g
7      Cranes  0.0       2      yes      h
8  spoonbills  8.0       3       no      i
9  spoonbills  4.0       2       no      j

**7. select the rows with columns ['birds', 'visits'] where the age is missing i.e NaN**

In [25]:
df.loc[df['age'] == 0]
df[df['age'] == 0]

birds  age  visits priority labels
3  spoonbills  0.0       4      yes      d
7      Cranes  0.0       2      yes      h

**8. Select the rows where the birds is a Cranes and the age is less than 4**

In [26]:
df.loc[((df['birds'] == 'Cranes') & (df['age'] < 4)) , ]
df[(df['birds'] == 'Cranes') & (df['age'] < 4)]

birds  age  visits priority labels
0  Cranes  3.5       2      yes      a
5  Cranes  3.0       4       no      f
7  Cranes  0.0       2      yes      h

**9. Select the rows the age is between 2 and 4(inclusive)**

In [27]:
df[(df['age'] >= 2) & (df['age'] <= 4)]

birds  age  visits priority labels
0      Cranes  3.5       2      yes      a
1      Cranes  4.0       4      yes      b
5      Cranes  3.0       4       no      f
9  spoonbills  4.0       2       no      j

**10. Find the total number of visits of the bird Cranes**

In [28]:
b=df.groupby('birds')
type(b)
for key,val in b:
    print(key,val['visits'].agg(['sum']))

Cranes sum    12
Name: visits, dtype: int64
plovers sum    5
Name: visits, dtype: int64
spoonbills sum    12
Name: visits, dtype: int64


**11. Calculate the mean age for each different birds in dataframe.**

In [29]:
b=df.groupby('birds')
type(b)
for key,val in b:
    print(key,val['age'].agg(['mean']))

Cranes mean    2.625
Name: age, dtype: float64
plovers mean    3.5
Name: age, dtype: float64
spoonbills mean    4.5
Name: age, dtype: float64


**12. Append a new row 'k' to dataframe with your choice of values for each column. Then delete that row to return the original DataFrame.**

In [31]:
df.loc[len(df.index)] = ['Cranes',	3.5,	2,	'yes','k']
df.drop(len(df.index)-1)

birds  age  visits priority labels
0      Cranes  3.5       2      yes      a
1      Cranes  4.0       4      yes      b
2     plovers  1.5       3       no      c
3  spoonbills  0.0       4      yes      d
4  spoonbills  6.0       3       no      e
5      Cranes  3.0       4       no      f
6     plovers  5.5       2       no      g
7      Cranes  0.0       2      yes      h
8  spoonbills  8.0       3       no      i
9  spoonbills  4.0       2       no      j

**13. Find the number of each type of birds in dataframe (Counts)**

In [32]:
#df.groupby('birds').agg(['count'])

b=df.groupby('birds')
type(b)
for key,val in b:
    print(key,val['birds'].agg(['count']))


Cranes count    5
Name: birds, dtype: int64
plovers count    2
Name: birds, dtype: int64
spoonbills count    4
Name: birds, dtype: int64


**14. Sort dataframe (birds) first by the values in the 'age' in decending order, then by the value in the 'visits' column in ascending order.**

https://pandas.pydata.org/pandas-docs/version/0.19/generated/pandas.DataFrame.sort.html

In [33]:
df.sort_values(['age', 'visits'], ascending=[0, 1])


birds  age  visits priority labels
8   spoonbills  8.0       3       no      i
4   spoonbills  6.0       3       no      e
6      plovers  5.5       2       no      g
9   spoonbills  4.0       2       no      j
1       Cranes  4.0       4      yes      b
0       Cranes  3.5       2      yes      a
10      Cranes  3.5       2      yes      k
5       Cranes  3.0       4       no      f
2      plovers  1.5       3       no      c
7       Cranes  0.0       2      yes      h
3   spoonbills  0.0       4      yes      d

**15. Replace the priority column values with'yes' should be 1 and 'no' should be 0**

In [34]:
df.loc[df['priority'] == 'yes', ['priority']] = 1
df.loc[df['priority'] == 'no', ['priority']] = 0

**16. In the 'birds' column, change the 'Cranes' entries to 'trumpeters'.**

In [35]:
#df.groupby('birds').get_group('Cranes')   = 'Cranes'
df.loc[df['birds'] == 'trumpeters', ['birds']] = 'Cranes'
#df.loc[df['birds'] == 'Cranes', ['birds']] = 'trumpeters'
df

birds  age  visits priority labels
0       Cranes  3.5       2        1      a
1       Cranes  4.0       4        1      b
2      plovers  1.5       3        0      c
3   spoonbills  0.0       4        1      d
4   spoonbills  6.0       3        0      e
5       Cranes  3.0       4        0      f
6      plovers  5.5       2        0      g
7       Cranes  0.0       2        1      h
8   spoonbills  8.0       3        0      i
9   spoonbills  4.0       2        0      j
10      Cranes  3.5       2        1      k

birds  age  visits priority
1  Cranes  4.0       4        1